### ISSUE TITLE
Handling 302 redirects

### ISSUE THREAD

**Issue by Bramjetten** [hotwired/turbo-android#120]
First of all: thank you for releasing Turbo-Android! ❤️ I'm eager to publish new Android apps.

### My Rails app
I'm using the native turbo-adapters on a Rails app using Turbolinks 5. 
My Rails app contains a model called `Dashboard`. On the initial load (`/app`) it will redirect the user to his first dashboard using `redirect_to @dashboard`.

### The issue
- On initial load (`/app`) on iOS this loads the dashboard view inside a webView, like expected. 
- On initial load (`/app`) on Android it follows the redirect and **opens it like an external URL**.

When clicking a link inside a webview that redirects to another page on the same domain:
- On iOS it adds the new view to the navigation stack, like expected.
- On Android it **opens the view like an external URL**.

Are we supposed to avoid using redirects with Turbo or is there something obvious I'm missing in my Android app?

I made two videos to showcase the issue:

https://user-images.githubusercontent.com/423116/103172909-385e7080-4857-11eb-84f9-20503b8dcf3f.mov 

https://user-images.githubusercontent.com/423116/103172910-3a283400-4857-11eb-8d79-9da72f2e701d.mov

**Comment by jayohms** [comment]
Hey @Bramjetten, there shouldn't be any correlation between redirects and opening urls externally. Are you using the demo app as a starting place? If so, check the logic in `NavDestination.shouldNavigateTo()` and the values in the `Constants` file. 

Let me know if that helps and happy to look further if there's something else going on.

**Comment by Bramjetten** [comment]
Thanks, I figured it out! 

I'm using the demo-app, and the `isNavigable` method checks whether the location starts with `BASE_URL`. I set `https://myrailsapp.com/app` as my BASE_URL, but that redirects to `/:account_id/dashboards/:id`, without the `/app` prefix.  

I've set `BASE_URL` to `htttps://myrailsapp.com` and `HOME_URL` to `$BASE_URL/app`. Works like expected now!
