### ISSUE TITLE
target=_blank doesn't work

### ISSUE THREAD

**Issue by chrisjenx** [hotwired/turbo-android#144]
I can't seem to handle/see/route `target=_blank` routes, they never seem to even reach `TurboSession.shouldOverrideUrlLoading`, I have logging on and never see any logs fired from those links.

We are using Turbolinks 5 on the web still and Turbo on Android, this is working fine with Turbolinks on Android, and does work with iOS using the new Turbo library interacting with Ruby Version 5. Wondering if it's a regression between New Android and Legacy Web?

If you need more insight to the website hopefully @cmartyn or @joemasilotti  can answer any questions.

**Comment by jayohms** [comment]
@chrisjenx I'm curious, is the `target=blank` link part of an `<iframe>` or some other embedded content on the page? I'm aware of an issue with `<iframe>` links, which I'll open a PR and fix. 

Ordinary `target=_blank` links should work, though, just like in the demo app: https://github.com/hotwired/turbo-native-demo/blob/main/views/index.ejs#L46-L49

**Comment by chrisjenx** [comment]
Oh I don't think so, but I do know I had to add `settings.setSupportMultipleWindows(true)` to enable opening files on the older version, so that should hopefully fix it here too.

**Comment by chrisjenx** [comment]
Oh nevermind, I have that turned on already...

**Comment by jayohms** [comment]
Interesting, if `settings.setSupportMultipleWindows(true)` is enabled, you also need to handle `WebChromeClient.onCreateWindow()`, so maybe that's the issue? 

I'll merge #145 over and ship a new beta and you can try it out. If that doesn't solve the issue you're running into, I'll need more specific steps to reproduce.

**Comment by jayohms** [comment]
[7.0.0-beta06](https://github.com/hotwired/turbo-android/releases/tag/7.0.0-beta06) is now available.

**Comment by chrisjenx** [comment]
Not sure if it was in an iframe or not, but yes that fixed it :partying_face:
