### ISSUE TITLE
Cookie not deleted after signing out

### ISSUE THREAD

**Issue by Bramjetten** [hotwired/turbo-android#148]
Cookies aren't always properly deleted in Turbo-Android. At first I thought my own Turbo-Android app was having issues, but I can reproduce this in the demo app:

- In the demo app there's a page where you need to "Login" to gain access to content. 
- After clicking sign out, it redirects to the index page where it looks like the authentication cookie is deleted. 
- After closing the app and restarting it, the cookie reappears and the user is signed in again. 

Here's a video:

https://user-images.githubusercontent.com/423116/108375666-76966180-7202-11eb-8644-efd9b0661228.mov

**Comment by jayohms** [comment]
Interesting, I'm not seeing this same behavior on my device. What WebView version is installed on your device?

**Settings -> System -> Advanced -> Developer Options**

![2021-02-18 10 43 30](https://user-images.githubusercontent.com/828317/108382173-89933c80-71d6-11eb-902b-e72bb1cb44e9.png)

**WebView implementation**

![2021-02-18 10 43 08](https://user-images.githubusercontent.com/828317/108382192-8d26c380-71d6-11eb-84d7-b5a8c35999ec.png)

**Comment by Bramjetten** [comment]
88.0.4324.152, same as you. Currently testing on a new Pixel 4a 5G, previously used an emulator which has the same issue. Also, I'm not quite sure why, but sometimes the issue is reversed. So after signing in and closing the app, when restarting it picks up the old session where no authentication cookie was set. It looks like it sometimes restores an old session with old cookies.

**Comment by jayohms** [comment]
> So after signing in and closing the app, when restarting it picks up the old session where no authentication cookie was set.

Ah ok, that's the behavior I'm seeing. In HEY, we have a native login flow and interact directly with the [`CookieManager`](https://developer.android.com/reference/android/webkit/CookieManager) to save cookies, so we haven't hit the same issue in production. 

I'll have to investigate this more, but I won't have time today. Let me know if you find a pattern between the two different behaviors that you've seen.

**Comment by Bramjetten** [comment]
I added a `flush()` call to `onVisitCompleted` in my `WebFragment`:

```kotlin
override fun onVisitCompleted(location: String, completedOffline: Boolean) {
    super.onVisitCompleted(location, completedOffline)

    // Persist cookies
    val cookieManager = CookieManager.getInstance()
    cookieManager.flush()
}
```

It seems this solves my issue. I'm far from an Android developer (my only experience with Android comes from your sample apps😅), so I'm not sure if this is a viable solution. It looks like Android already persists cookies, just not always when I want it too. 

Do you think calling `flush` on every `visitCompleted` could cause problems?

**Comment by jayohms** [comment]
Great to know! I don't anticipate that this would cause any issues. It's possible this issue exists because `WebView` doesn't see Turbo visits as actual page loads due to its SPA nature.

I'll test this more and move this to an internal library concern, since the issue will exist for all apps.

**Comment by jayohms** [comment]
@Bramjetten I've just added a permanent solution in #150 to address this issue and it avoids flushing cookies on every visit. It will be available in the upcoming `7.0.0-beta08` and I recommend removing your `onVisitCompleted()` solution once that's available.

Closing this, but let me know if you run into issues on `beta08`.

**Comment by jayohms** [comment]
@Bramjetten Version `7.0.0-beta08` is now available, which includes the cookie fix: https://github.com/hotwired/turbo-android/releases/tag/7.0.0-beta08

**Comment by Bramjetten** [comment]
Thanks!
