### ISSUE TITLE
When compare locations, only path is compared, params are ignored

### ISSUE THREAD

**Issue by fffx** [hotwired/turbo-android#157]
As you can see in [TurboNavRule](https://github.com/hotwired/turbo-android/blob/main/turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavRule.kt)
```
    private fun locationPathsAreEqual(first: String?, second: String?): Boolean {
        if (first == null || second == null) {
            return false
        }

        return URI(first).path == URI(second).path
    }
```

This will cause unexpected pop presentation.  Shouldn't params be compared too? Since params also reflect page state.

**Comment by jayohms** [comment]
Can you describe the scenario where this is causing issues in your app? I'd like a better understanding, to see if our apps differ in how we use query params. Currently, if the location paths are identical, but the query params are different, we'll `REPLACE` the current destination with the new destination. 

We use query params sparingly in our apps, essentially only using them to filter or sort the display of items on a screen. But I can see how a liberal use of query params might lead to undesired behavior with the current logic.

**Comment by fffx** [comment]
First I visit  `/ledgers`, the ledger show page(displaying the first ledger id=1)

then I visit `/ledgers/list`, then I click on a link `/ledgers?id=2`, expect to visit `/ledgers?id=2`, but a pop presentation loaded.

```
D/TurboLog: visitProposedToLocation ........... [session: main, location: https://localhost.dev/ledgers?ledger_id=2, options: TurboVisitOptions(action=ADVANCE, snapshotHTML=null, response=null)]
D/TurboLog: shouldNavigateToLocation .......... [session: main, location: https://localhost.dev/ledgers?ledger_id=2, shouldNavigate: true, fragment: WebHomeFragment]
D/TurboLog: navigate .......................... [session: main, location: https://localhost.dev/ledgers?ledger_id=2, options: TurboVisitOptions(action=ADVANCE, snapshotHTML=null, response=null), currentContext: DEFAULT, newContext: DEFAULT, presentation: POP, fragment: WebHomeFragment]
D/TurboLog: navigateWithinContext ............. [session: main, location: https://localhost.dev/ledgers?ledger_id=2, presentation: POP, fragment: WebHomeFragment]
D/TurboLog: fragment.onStop ................... [session: main, location: https://localhost.dev/ledgers/list, fragment: WebHomeFragment]
D/TurboLog: fragment.onActivityCreated ........ [session: main, location: https://localhost.dev/ledgers, fragment: WebFragment]
D/TurboLog: fragment.onStart .................. [session: main, location: https://localhost.dev/ledgers, fragment: WebFragment]
D/TurboLog: visitLocation ..................... [session: main, location: https://localhost.dev/ledgers, options: TurboVisitOptions(action=RESTORE, snapshotHTML=null, response=null), restorationIdentifier: 84b63bd4-1225-4bc9-8606-8c401d78c143]
D/TurboLog: visitStarted ...................... [session: main, location: https://localhost.dev/ledgers, visitIdentifier: 5c9be816-84a2-4336-b923-68903b67d67d, visitHasCachedSnapshot: true]
D/TurboLog: visitRendered ..................... [session: main, visitIdentifier: 5c9be816-84a2-4336-b923-68903b67d67d]
```

I knew the route is weird, but it shouldn't cause a problem?

**Comment by jwark** [comment]
I agree that this is a bug @fffx , having similar problems on a project myself.

**Comment by jayohms** [comment]
@fffx @jwark I've changed the default behavior in #178, but have added a new path property configuration option to restore the previous behavior for any desired paths.

**Comment by jwark** [comment]
> @fffx @jwark I've changed the default behavior in #178, but have added a new path property configuration option to restore the previous behavior for any desired paths.

Thanks @jayohms for putting in the effort to get this fixed and for letting us know, I really appreciate it. :)
