### ISSUE TITLE
attachWebView Crash

### ISSUE THREAD

**Issue by chrisjenx** [hotwired/turbo-android#162]
Saw this on Android 10 Motorola yesterday.

```
Fatal Exception: java.lang.IllegalStateException
The specified child already has a parent. You must call removeView() on the child's parent first.
dev.hotwire.turbo.views.TurboView$attachWebView$1.run
android.view.ViewGroup.addViewInner (ViewGroup.java:5109)
android.view.ViewGroup.addView (ViewGroup.java:4938)
android.view.ViewGroup.addView (ViewGroup.java:4878)
android.view.ViewGroup.addView (ViewGroup.java:4851)
dev.hotwire.turbo.views.TurboView$attachWebView$1.run (Unknown Source:8)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:241)
android.app.ActivityThread.main (ActivityThread.java:7582)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:941)
```

Android 10
motorola edge
8 Mar 2021, 08:57:48

**Comment by jayohms** [comment]
We've seen this occasionally in our crash reports, too. But I haven't narrowed down the cause yet. I plan to fix this once it's reproducible. Let me know if you have any additional insights.

**Comment by chrisjenx** [comment]
@jayohms yeah not enough reports outside yet to see where it happens, If I reproduce I'll post.

**Comment by chrisjenx** [comment]
So far these seem to happen on a cold start.

```
Parameters
firebase_screen_class: SplashActivity
3
03:49:36.110 pm
screen_view
Parameters
firebase_screen_class: MainTurboActivity
```

I also have a hunch this started happening after I changed how we handled push, from onCreate -> onResume

**Comment by ghiculescu** [comment]
I can replicate this on a cold start. In our case, it's happening if the app boots from a [deep link](https://firebase.google.com/docs/dynamic-links/android/receive), then we call `delegate.navigate` from `MainActivity#onCreate`.

**Comment by jayohms** [comment]
I recommend waiting until `Activity.onResume()` to handle incoming deep link intents — this seems to work well on our end. We have plans this year to provide deep link navigation behavior out-of-the-box, but until then there aren't any immediate plans to address this issue.
