### ISSUE TITLE
Can I use js getCurrentPosition in webview ? 

### ISSUE THREAD

**Issue by Nodalailama** [hotwired/turbo-android#165]
Hi,

I am trying to use js getCurrentPosition in some of my webviews ... but, even with the correct permissions, at the start of the app, it's not working.

May I need to add setGeolocationEnabled like there is a setJavaScriptEnabled in TurboSession.kt file.

Thanks in advance.

**Comment by vdegove** [comment]
Hey @Nodalailama! The issue is closed, have you found a solution for this? (Needing to acces getCurrentPosition too)

**Comment by Nodalailama** [comment]
Hey,

That is great because I gonna to push a commit for you :) I find the way to do it by add some line of code in your code.
I push it by this day.

Cordialement,

**Comment by Nodalailama** [comment]
It's pushed.

**Comment by jumshaidkhan** [comment]
Hi @Nodalailama and @vdegove 

I have tried the code @Nodalailama has committed to fixing getCurrentPosition in webview. 

`override fun onGeolocationPermissionsShowPrompt(origin: String?, callback: GeolocationPermissions.Callback) {
        callback.invoke(origin, true, false)
    }`

But, still, I am unable to get the current position. Any other fix? or something that I am doing wrong? 

I have the following permissions enabled for now
`<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />`
