### ISSUE TITLE
demo gives a ssl error when using a different BASE_URL

### ISSUE THREAD

**Issue by TopRoupi** [hotwired/turbo-android#212]
only thing i changed in the demo was setting BASE_URL to https://www.greyrepo.xyz

after running the application it will show the default error page on the phone screen and show this error on the logs

![image](https://user-images.githubusercontent.com/38011914/151036060-7ec5c03d-8b07-4681-b3e2-657bc0778ddc.png)

**Comment by jayohms** [comment]
What `WebView` version is running on your device? Turbo doesn't handle any SSL logic, it's all handled directly by the device's underlying `WebView`. If you're on an updated version, you should see it based on Chromium 96.x or 97.x.

**Comment by TopRoupi** [comment]
it was indeed a problem with the version, i updated the emulator sdk version and it is working now.
