### ISSUE TITLE
Content pulled up excessively on input focus

### ISSUE THREAD

**Issue by silva96** [hotwired/turbo-android#215]
Just wrapped my website into a turbo android app without anything extra from the android side.

This is the behaviour when tapping an input.

https://user-images.githubusercontent.com/4019924/154824374-b36497ef-2fcd-4f32-a89e-56fb4f88a401.mp4

This does not happen on the website itself (https://profe.social/users/sign_in)

This happens on every single input, not just the one in the video

**Comment by jayohms** [comment]
You can consider using a different `windowSoftInputMode`, such as `adjustPan` in your app's manifest file, otherwise this it out of scope for the library:
```xml
android:windowSoftInputMode="adjustPan"
```
