### ISSUE TITLE
Getting demo to work with localhost rails app

### ISSUE THREAD

**Issue by DanielJackson-Oslo** [hotwired/turbo-android#221]
Thank you for an excellent contribution to the eco system!

I'm trying to test out `turbo-android` and `turbo-ios` in a greenfield Rails 7 app.

For `turbo-ios`, set up to use localhost was [well documented](https://github.com/hotwired/turbo-ios/blob/fadb1f3888427a839f1e102ec5f38125f96172ba/Demo/Demo.swift#L10), and easy to do: 

```swift

struct Demo {
    static let local = URL(string: "http://localhost:3000")!

    static var current: URL {
        local
    }
}

```

But for `turbo-android` I haven't managed to get localhost to work, after a few hours of trying, neither with `localhost:3000` or a custom local domain `dev.local:3000` (however it works fine with an online production rails 7 app I also control):

I've tried to change BASE_URL in [Constants.kt](https://github.com/hotwired/turbo-android/blob/556cfae61408811fe488bd877416b27e53cb35ca/demo/src/main/kotlin/dev/hotwire/turbo/demo/util/Constants.kt)

```kotlin
// In Constants.kt
const val BASE_URL = "http://dev.local:3000"
```
and

```kotlin
// In Constants.kt
const val BASE_URL = "http://localhost:3000"
```

I get the following error message in the emulator, and while I've tried to look for logs to see what's going on, I'm not very well versed in Android Studio and haven't found anything useful there:

<img width="314" alt="image" src="https://user-images.githubusercontent.com/14905290/159117031-f750de7a-f181-4010-95c0-eb15fe1419f5.png">

Any idea why this might be the case?

**Comment by svantepolk** [comment]
localhost refers to the emulator itself; you'll probably want to use 10.0.2.2 instead.

[https://developer.android.com/studio/run/emulator-networking#networkaddresses](https://developer.android.com/studio/run/emulator-networking#networkaddresses)

**Comment by DanielJackson-Oslo** [comment]
Thank you! That worked :)
