### ISSUE TITLE
Offline-first (aka local-first) use

### ISSUE THREAD

**Issue by dumblob** [hotwired/turbo-android#222]
I wonder whether there are any plans for adopting the offline-first/[local-first](https://www.inkandswitch.com/pushpin/ ) approach?

After many many years I think Turbo (and the ecosystem around) is in the best position among web-based or web-related technologies to make it happen.

Note I'm not advocating here advanced stuff like https://github.com/josephg/diamond-types (CRDTs on steroids) or [Causal Trees](https://github.com/josephg/diamond-types/issues/6 ).

I'd just like to support the workflow: "edit offline during long stay (hours to weeks) without internet, then synchronize automatically with manual merging in case of conflict".

Any thoughts?

**Comment by Nodalailama** [comment]
Hi,

An hybrid application, like built with turbo-android, rely on the internet most of time.

Best regards

**Comment by dumblob** [comment]
That's why I'm seeking the offline-first/local-first support :wink:.

**Comment by jayohms** [comment]
We plan to explore service workers for first-class offline support across all platforms. Until then, there are no immediate plans in this project.

**Comment by nfacciolo** [comment]
Waiting for this upgrade ! <3

Do you know when you plan to work on that ?
