### ISSUE TITLE
No back button when MainActivity is not a TurboActivity

### ISSUE THREAD

**Issue by annajeanine** [hotwired/turbo-android#227]
In the current app I'm working on the setup differs from the demo setup. In the demo setup, the `MainActivity` uses the `TurboActivity` class. In my current setup, I have native authentication and therefore the `MainActivity` handles part of the authentication. When the user is authenticated, they are passed to the `WebActivity`. The `WebActivity` contains all needed and uses the `WebFragment` as in the demo. 

However, when testing the app right now, the 'back' button has disappeared. I have searched the source code, but no luck. Is the `TurboNavGraphBuilder` required to use the `MainActivity` as registered activity? I have tried registering the `WebActivity`, but no luck. 

Could someone help me out with this?

**Comment by annajeanine** [comment]
@jayohms Thank you! Managed to fixed it with the following code in my `WebFragment` 

```
toolbarForNavigation()?.apply {
    inflateMenu(R.menu.web)
    setNavigationIcon(R.drawable.ic_round_arrow_back_24)
    setNavigationOnClickListener {
        navigateBack()
    }
}
```

Works like a charm for anyone interested 👍

**Comment by kyrylo** [comment]
Could you please provide an example of how to use multiple activities?

I followed the multiple activities doc, but after annotating them, I got an error:

```
Caused by: java.lang.IllegalArgumentException:
A start Fragment destination was not found for uri: turbo://activity/login
```

```kt
@TurboNavGraphDestination(uri = "turbo://activity/main")
class MainActivity : AppCompatActivity(), TurboActivity {
```

```kt
@TurboNavGraphDestination(uri = "turbo://activity/login")
class LoginActivity : AppCompatActivity(), TurboActivity {
```

```json
{
  "patterns": [
    "^/sign_in$",
    "^/sign_up$"
  ],
  "properties": {
    "uri": "turbo://activity/login",
    "pull_to_refresh_enabled": false
  }
},
```

From what I understand, I need to create a `res/navigation` file, but I only want to hide the bottom navigation on my login pages (and display it when you're signed in). Not sure if this is the way to go, any help is greatly appreciated!
