### ISSUE TITLE
Version naming convention

### ISSUE THREAD

**Issue by svantepolk** [hotwired/turbo-android#239]
NIT:

Android studio uses lexicographic ordering to try to figure out which version is the latest, which breaks down when you go from 9 to 10. Maybe add leading 0's to make this more accurate?

<img width="513" alt="Screen Shot 2022-08-17 at 10 55 27 am" src="https://user-images.githubusercontent.com/25386350/185010487-8cb809e9-480b-4dd5-8d21-e9f6e1c7c351.png">

**Comment by jayohms** [comment]
Thanks, I doubt we'll hit this again now that we're on stable versions 👍
