### ISSUE TITLE
Why is it impossible to use pinch to zoom ?

### ISSUE THREAD

**Issue by jean-francois-labbe** [hotwired/turbo-android#256]
I'm using turbo-android and I'd like to allow users to zoom-in some images.
How can I do that ?

I've checked the viewport: `<meta content="width=device-width, initial-scale=1, user-scalable=1" name="viewport">`
Tried to use `webView.settings.setSupportZoom(true)` without success.

**Comment by jayohms** [comment]
We use the following `viewport` attributes in the HEY app when we conditionally enable page zoom:
```
width=device-width, initial-scale=1, maximum-scale=2.5
```

Additionally, on the Android side, we set:
```kotlin
webView.settings.builtInZoomControls = true
webView.settings.displayZoomControls = false
```

**Comment by jean-francois-labbe** [comment]
Thanks a lot. indeed it's working now.
