### ISSUE TITLE
How to localize bundled path configuration?

### ISSUE THREAD

**Issue by sedubois** [hotwired/turbo-android#270]
The [documentation](https://github.com/hotwired/turbo-android/blob/main/docs/PATH-CONFIGURATION.md#path-configuration) instructs to store a Path Configuration JSON in the project; what is the proper way to store several of these, one per supported language, or alternately how to make sure the strings and URLs contained in this file get localized?

**Comment by donnfelker** [comment]
One way this could be done is by building many config files and endpoints to handle your various languages. In [Jumpstart Pro Android](https://jumpstartrails.com/android) we have this method in the `MainSessionNavHostFragment.kt`: 

```kotlin
override val pathConfigurationLocation: TurboPathConfiguration.Location
        get() = TurboPathConfiguration.Location(
            assetFilePath = LOCAL_CONFIG_FILE,
            remoteFileUrl = REMOTE_CONFIG_URL
        )
```

Instead of using constants, you could build a path based on the System locale of the device. 

Examples: 
- English: `configuration_en.json` 
- Spanish: `configuration_es.json`
- French: `configuration_fr.json`

The server would have multiple remote endpoints that might be similar in nature: 
- English: `/android/path_configuration_en.json` or `/en/android/path_configuration.json`
- Spanish: `/android/path_configuration_es.json` or `/es/android/path_configuration.json`
- French: `/android/path_configuration_fr.json` or `/fr/android/path_configuration.json`

Then your method might look like this (pseudocode): 
```kotlin
override val pathConfigurationLocation: TurboPathConfiguration.Location
        get() = TurboPathConfiguration.Location(
            assetFilePath = localConfigFor(Locale.getDefault().language),
            remoteFileUrl = remoteConfigFor(Locale.getDefault().language)
        )

fun localConfigFor(language: String?): String {
  return "configuration_$language.json"
}

fun remoteConfigFor(language: String?): String {
  return "/android/configuration_$language.json"
}
```

Then, in your various remote configs you'd set up different paths for different languages/etc if you needed to do so. 

Would that work?

**Comment by sedubois** [comment]
The above works for loading the correct path config at boot, but it leaves the app in an incoherent state when the user [changes their language](https://developer.android.com/guide/topics/resources/app-languages#api-implementation): the new string resources get loaded but the tabs are still in the old language.

NB: here is my code to ensure the translated page first loads before changing the language client-side.

Server-side:
```erb
<% I18n.with_locale(new_locale) do %>
    <%= link_to "switch to new language", url_in_new_locale,
              data: { controller: "language",
                      action: "language#updateClientLanguage",
                      'settings-language-value': I18n.locale } %>
<% end %>
```
```js
// javascript/controllers/index.js
import LanguageController from "./language_controller.js"
application.register("language", LanguageController)
```
```js
// javascript/controllers/language_controller.js
import { Controller } from "@hotwired/stimulus"
import { isTurboNative } from "../lib/environment"

export default class extends Controller {
  static get values() {
    return { language: String }
  }

  static get shouldLoad() {
    return isTurboNative;
  }

  updateClientLanguage() {
    // update client right after the web page has switched to the new language
    document.addEventListener('turbo:load', () => {
      window.TurboNativeBridge.postMessage("selectLanguage", { language: this.languageValue })
    }, { once: true })
  }
}
```

Client-side:

```kts
// build.gradle.kts
dependencies {
    ...
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.appcompatResources)
}
```
```toml
# gradle/lib.versions.toml
androidXAppCompat = "1.6.1"
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidXAppCompat" }
androidx-appcompatResources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "androidXAppCompat" }
```
```kt
    // Trigger this code when receiving the `selectLanguage` JS event
    // e.g. with Jumpstart Pro Android, add this to `MainSessionNavHostFragment`
    // and bind it in bindNativeBridge(webView: TurboWebView)
    // with `nativeAppJavaScriptInterface.onLanguageSelected = ::onLanguageSelected`
    private fun onLanguageSelected(languageTag: String) {
        AppCompatDelegate.setApplicationLocales(forLanguageTags(languageTag))
        
        // TODO: how to reload path config and update toolbar title?

        // This does not seem to do anything:
        // reset()

        // This does switch the language of the navigation tabs and toolbar,
        // BUT the app gets minimized and the Android home screen is shown
        // Handler(Looper.getMainLooper()).post(::reset)

        // This "restarts" the app while keeping it visible, BUT:
        // - goes back to the initial screen (current page is lost)
        // - keeps the old web view running, according to what I see in the chrome debugger
        // val context = context ?: return
        // val name = ComponentName(context, MainActivity::class.java)
        // val intent = makeRestartActivityTask(name)
        // startActivity(intent)
    }
```

@donnfelker would you know how to cleanly refresh the app language (see issues mentioned in the above code)?

NB: The above in-app language switching could be combined with Android 13's new [app language settings screen](https://developer.android.com/guide/topics/resources/app-languages#app-language-settings). But it would also be necessary to restart the app when the language is changed there. How to do that?

**Comment by donnfelker** [comment]
@sedubois You will need to respond to `Activity#onConfigurationChanged` most likely. From there you'll need to reload the views and/or tell Compose to re-render/recompose itself. More info: https://stackoverflow.com/a/33889985/5210 - I'm assuming this would be in `MainActivity` in JSP Android. 

This might require some additional work to get the config to reload. In the `MainSessionNavHostFragment` you will probably need to make some changes to the `onSessionCreated` method and tell it to reload the session config somehow. I havent dove too deep into it, but those are a couple things I'd look at.

**Comment by sedubois** [comment]
Thanks @donnfelker! I got something working. At the moment I'm not even adding a `MainActivity#onConfigurationChanged` override because it wasn't really necessary. Also in the beginning I didn't understand that for onConfigurationChanged to actually be called, I would have needed to add `android:configChanges="layoutDirection|locale"` to `<activity ...></activity>` in AndroidManifest.xml.

Here is the outline of the solution:
1. Unlike stated above, in this implementation the server does not switch language before initiating the switch client-side. Instead, the user's click just triggers a JS event sending the native app the newly desired language and the URL or the new page, without performing any actual navigation.
2. when receiving this message, the JS bridge saves the URL to SharedPreferences (any better way to transmit that info?), then initiates a change of the Android app locale using `AppCompatDelegate.setApplicationLocales`.
3. At this stage, the Android app's resources change to the new language, so if the UI is showing e.g. a string with `getString(R.string.my_string)`, it will properly show up in the new language. However, the web page, top and bottom tab bar still need to be changed.
4. As `android:configChanges="layoutDirection|locale"` isn't added in the Android manifest, it means that instead the whole activity will get recreated and `MainActivity#onCreate` will get called.
5. In `MainActivity#onCreate`, the code needs to be adapted to instruct `mainActivityViewModel` to recreate its tabs based on the path configuration in the new locale. 
6. As the activity is still initializing, it's too early to already navigate to the new URL at this stage. Instead, the viewModel state should be observed in a lifecycle-aware manner (`...observe(this) { ... }`). The code passed in the block will then only be executed when the activity is properly recreated.
7. At this point, the URL can be retrieved from SharedPreferences and passed to Turbo to change the actual page contents to the new language. Thanks to the fact that the page contents are changed *after* the native app locale is changed, the top bar will be in a correct state. In practice thanks to this, the menu icon will be visible instead of a back arrow.

Rails:

```erb
<% I18n.with_locale(new_locale) do %>
    <%= link_to "switch to new language", url_in_new_locale,
              data: { controller: "language",
                      action: "language#setLanguage",
                      'language-tag-value': I18n.locale, 'language-url-value': url_in_new_locale } %>
<% end %>
```

```js
// javascript/controllers/index.js
import LanguageController from "./language_controller.js"
application.register("language", LanguageController)
```

```js
// javascript/controllers/language_controller.js
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  static get values() {
    return { tag: String, url: String }
  }

  setLanguage(event) {
    event.preventDefault()
    event.stopImmediatePropagation()
    window.TurboNativeBridge.postMessage("setLanguage", { language: this.tagValue, url: this.urlValue })
  }
}
```

Android:

```kt
// NativeAppJavaScriptInterface.kt
var onSetLanguage: (tag: String, url: String) -> Unit = { _, _ -> }

fun postMessage(jsonData: String?) {
    ...
    when (val command = json.optString("name")) {
        ...
        SET_LANGUAGE -> onSetLanguage(json.optString("language"), json.optString("url"))
    }
}
```
```kt
// MainSessionNavHosFragment.kt
        nativeAppJavaScriptInterface.onSetLanguage = { language, url ->
            (activity as? MainActivity)?.let {
                it.languageSwitchingUrl = url
                Handler(Looper.getMainLooper()).post {
                    AppCompatDelegate.setApplicationLocales(forLanguageTags(language))
                }
            }
        }
```
```kt
// Constants.kt
const val LANGUAGE_SWITCH_URL_KEY = "language-switch-url"
```

```kt
// MainActivity.kt
    @Inject lateinit var sharedPreferences: SharedPreferences

    var languageSwitchingUrl: String?
        get() = sharedPreferences.getString(LANGUAGE_SWITCH_URL_KEY, null)
        set(value) = sharedPreferences.edit().putString(LANGUAGE_SWITCH_URL_KEY, value).apply()

    ...

    override fun onCreate(savedInstanceState: Bundle?) {
        ... 
        mainActivityViewModel.loadNavItems().observe(this) {
            delegate.navigate(languageSwitchingUrl ?: startUrl)
            languageSwitchingUrl = null
        }
        ...
    }
```
```kt
// MainActivityViewModel.kt
    fun loadNavItems(): MutableLiveData<List<NavigationTabData>> {
        return liveDataNavItems.apply { value = jumpstartConfiguration.getBottomMenuItems() }
    }

```
