### ISSUE TITLE
Styling the "page loading" spinner

### ISSUE THREAD

**Issue by pauljacksonrodgers** [hotwired/turbo-android#275]
When navigating from one web fragment to another, there is a brief moment when the new page is being loaded, where I see the loading spinner animation. In that window, the background color flashes to either pure white or pure black depending on whether the system is in light or dark mode.

Is there a way to configure the color of the background under that loading animation to make the transitions less jarring?

**Comment by pauljacksonrodgers** [comment]
Nevermind! I figured out I could override `createProgressView` and call `view.setBackgroundColor` in there 👍

**Comment by leon-vogt** [comment]
The comment that we can override `createProgressView` and call `view.setBackgroundColor` helped me.
Thank you! 😄
