### ISSUE TITLE
How to from FirstActivity to SecondActivity and how to use replace_root

### ISSUE THREAD

**Issue by eserna27** [hotwired/turbo-android#278]
Hi, I try to build my first project using Turbo-android, and I want to change activity but if I change in the path Configuration for an activity URI my project crash.

And the other question is about to use replace_root if use it with the another type of fragment the action is push not replace_root, How is the best way to use this type of presentation.

**Comment by michalsznajder** [comment]
> Hi, I try to build my first project using Turbo-android, and I want to change activity but if I change in the path Configuration for an activity URI my project crash.

Any chance you can provide stack trace?

**Comment by jayohms** [comment]
Not enough details to reproduce.
