### ISSUE TITLE
Fullscreen button not working for embedded YouTube video

### ISSUE THREAD

**Issue by astroblemeal** [hotwired/turbo-android#279]
The fullscreen button is not functioning correctly when attempting to open fullscreen mode for embedded YouTube videos. We have found a Medium article ([Fullscreen YouTube Video in WebView Android](https://oliverbozhinovski.medium.com/fullscreen-youtube-video-in-webview-android-21f1c778cf56)) that suggests setting up a custom WebChromeClient as a potential solution.

However, we are unsure if this customisation is compatible. We kindly request guidance from the community or framework maintainers if anyone has encountered a similar issue and found a resolution.

It's worth noting that the fullscreen button works perfectly in our iOS app, which also utilizes the Turbo framework.

**Comment by jayohms** [comment]
You can provide your own `TurboWebChromeClient` subclass implementation in any `TurboWebFragment` like:
```kotlin
override fun createWebChromeClient(): TurboWebChromeClient {
    return MyWebViewChromeClient(session)
}
```

For specifics about YouTube videos, the community forum would be a better place for help: https://discuss.hotwired.dev/
