### ISSUE TITLE
Not possible to customize animation for replace_root

### ISSUE THREAD

**Issue by MichalSznajder** [hotwired/turbo-android#285]
When animation is customized via `getNavigationOptions` it is ignored when `"presentation": "replace_root"` is used. This makes issues like #181 unsolvable. If you have toolbar (either native or in html) and use `"replace_root"` to navigate between tabs there will be always a white flash.

**Comment by leonvogt** [comment]
I spend hours figuring out where this white flash is coming from...
In the end my hacky solution was to override the default animation by creating the following files:

- res/anim/nav_default_enter_anim.xml
- res/anim/nav_default_exit_anim.xml
- res/anim/nav_default_pop_enter_anim.xml
- res/anim/nav_default_pop_exit_anim.xml

And fill them with basically nothing:
```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <!-- Empty to disable animation -->
    <!--
        The default animation would trigger a blink / flash effect on the Appbar.
        Therefore, we disable the animation here.
     -->
</set>
```

**Comment by michalsznajder** [comment]
@leonvogt Are you using custom compilation of Turbo in your project? Those files look like ones in Turbo Android source code.

**Comment by leonvogt** [comment]
You are correct; those are the default Android animations that are being overridden by this.     
It's definitely not an elegant solution, but it's the only one I found to remove the flash effect on a custom toolbar.

**Comment by jayohms** [comment]
Resolved in https://github.com/hotwired/turbo-android/pull/304
