### ISSUE TITLE
Handle navigations to files by default

### ISSUE THREAD

**Issue by lazaronixon** [hotwired/turbo-android#290]
Extract these fragments in the demo or handle this navigation by default.
hey://fragment/downloads
hey://fragment/image_viewer
hey://fragment/downloads

**Comment by jayohms** [comment]
We have plans this year to provide more default behavior and capabilities out of the box 👍

**Comment by janpeterka** [comment]
How was this solved for downloads? Was looking in the new `hotwire-native-android` docs and github project, cannot find that anywhere.
