### ISSUE TITLE
Clear back stack but keep the current location

### ISSUE THREAD

**Issue by reaper** [hotwired/turbo-android#295]
Hi, just try to clear the back stack but keep the current location as the start location.

An first try would be
```kotlin
activity.runOnUiThread {
    (activity.delegate.currentSessionNavHostFragment as MaloSessionNavHostFragment).let {
        it.currentNavDestination.location.let { currentLocation ->
            if (it.startLocation != currentLocation) {
                it.startLocation = currentLocation
                it.reset()
            }
        }
    }
}
```

but it hangs when calling back.

Any idea of how I can achieve this? Thank you!

**Comment by jayohms** [comment]
You can call `clearBackStack()` from any `Fragment` destination, which should get you the desired result.
