### ISSUE TITLE
AmbiguousViewMatcherException on TurboWebViews & cannot set unique identifiers

### ISSUE THREAD

**Issue by graial** [hotwired/turbo-android#312]
Greetings,

I have 3 TurboWebViews, (one for each tab in my navigation bar).  When I try to access them via espresso-web, I get an ambiguous match:

> androidx.test.espresso.AmbiguousViewMatcherException: 'an instance of android.webkit.WebView and webView.getSettings().getJavaScriptEnabled() is <true>' matches 3 views in the hierarchy:
> - [1] TurboWebView{id=-1, visibility=VISIBLE, **width=1080, height=1437**, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0}
> - [2] TurboWebView{id=-1, visibility=VISIBLE, **width=0, height=0**, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0}
> - [3] TurboWebView{id=-1, visibility=VISIBLE, **width=0, height=0**, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0}

this [espresso-web sample](https://github.com/android/testing-samples/blob/main/ui/espresso/WebBasicSample/app/src/androidTest/java/com/example/android/testing/espresso/web/BasicSample/WebViewActivityTest.java) (line 108) recommends trying to resolve an ambiguous match via the id. However, in the view hierarchy above you can see that the id for all three is -1 (i guess null?)

I tried adding `android:contentDescription="home_web_view"` and also `android:tag="home"` but neither of those show up in the view hierarchy.
In the above, I marked the height and width in bold to show that is a unique matcher I could use.  I tried to target them using custom matchers but couldn't get a match. I'm not sure, but maybe because custom matchers in espresso can't target webviews/turbowebviews ?

Also tried using a few different custom matchers to try and target the first element and also failed to get a match.

The code for setting the fragments is:
```
setContentView(R.layout.activity_main_nav_flagged)

delegate = TurboActivityDelegate(this, tabsViewModel.tabs.first().id)

tabsViewModel.tabs.forEach {
      delegate.registerNavHostFragment(it.id)
}
tabSwitcher = findViewById(R.id.tabSwitcher)

tabBar = findViewById(R.id.tabBar)

tabBar.setOnItemSelectedListener {
    tabSwitcher.displayedChild = tabsViewModel.indexedTabForId(it.itemId)!!.index
    delegate.currentNavHostFragmentId = it.itemId
    (delegate.currentSessionNavHostFragment.currentNavDestination as NavDestination).dismissLoginScreen()

   delegate.refresh(false)

   return@setOnItemSelectedListener true
}
```

Should I expect to be able to set unique identifiers on TurboWebViews in the current version?  Alternatively, is this a feature that needs to be implemented?

**Comment by jayohms** [comment]
@graial does this solve your issue? https://github.com/hotwired/turbo-android/pull/315

You can get the unique ID for each `WebView` from its `TurboNavHostFragment` instance:
```kotlin
session.webView.id
```

**Comment by graial** [comment]
Hi @jayohms,

This is good.  We are definitely in the right spot of the code. In the init constructor, I also added 
`contentDescription = "test"`

So now my view hierarchy returns

> - [1] TurboWebView{id=1, desc=test, ...}
> - [2] TurboWebView{id=2, desc=test, ...}
> - [3] TurboWebView{id=3, desc=test, ...}
> 

Now, when I try to target the elements with espresso-web: 
- `onWebView(withId(1))` times out with:
> java.lang.RuntimeException: java.lang.RuntimeException: Atom evaluation returned null!

- `onWebView(withContentDescription("test"))` also returns:
AmbiguousViewMatcherException.
So i am successfully matching against contentDescription`.

So if I can now pass data to the `init` constructor, then that should get the job done.

I'm guessing that I need to set this in my `WebFragment.kt`. I have the following overrides which seem relevant (delegated via Strada)
```
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setupMenu()
        viewLifecycleOwner.lifecycle.addObserver(bridgeDelegate)
    }
```
&
```
    override fun onWebViewAttached(webView: TurboWebView) {
        bridgeDelegate.onWebViewAttached(webView)
    }
```

Is one of these where I would pass in the id &/or content description?

My `activity_main.xml` has the following structure (many tags removed for brevity):

```
<androidx.constraintlayout.widget.ConstraintLayout
    android:id="@+id/turbo_constraint"
    tools:context=".MainActivity">

    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/tabBarDisabled"
        app:menu="@menu/tabs"
        />

    <ViewFlipper
        android:id="@+id/tabSwitcher">

        <androidx.fragment.app.FragmentContainerView
            android:id="@+id/tab_home"
            android:name="com.sune.booking.SessionNavHostFragment"
            android:contentDescription="home_web_view"
            android:tag="home"
            />
        <androidx.fragment.app.FragmentContainerView
            android:id="@+id/tab_shop"
            android:contentDescription="content_web_view"
            android:name="com.sune.booking.SessionNavHostFragment"
            android:tag="shop"
            />
        <androidx.fragment.app.FragmentContainerView
            android:id="@+id/tab_profile"
            android:contentDescription="profile_web_view"
            android:name="com.sune.booking.SessionNavHostFragment"
            android:tag="profile"
            />
    </ViewFlipper>
</androidx.constraintlayout.widget.ConstraintLayout>
```

The id, content_description & tag all show up for the FragmentContainerView in the view hierarchy successfully.  Would it be possible to pass the data in from the container by chance?

Take care,
Allan

**Comment by jayohms** [comment]
Hmmm, I'm not sure how setting the `contentDescription` would resolve this for you. If an `id` match doesn't work, I'm not sure how a `contentDescription` match would work either. 

You can always set your own description via `webview.contentDescription = "home"` in the code anywhere since it's a public method. An example would be in your `SessionNavHostFragment`:
```kotlin
class SessionNavHostFragment : TurboSessionNavHostFragment() {
    // ...

    override fun onCreateWebView(context: Context): TurboWebView {
        return super.onCreateWebView(context).also { 
            it.contentDescription = "home"
        }
    }
}
```

However, I see that you're using the same `com.sune.booking.SessionNavHostFragment` instance for all your tabs — this should be avoided. You should use a unique `TurboSessionNavHostFragment` subclass instances for each tab. Each session requires its own `sessionName` and `startLocation`.

**Comment by graial** [comment]
Good news! taking your suggestion, I was able to set a unique contentDescription with:
`it.contentDescription = "web_view_$tag"`
where _tag_ is set in the FragmentContainerView with `android:tag="home"`

this matches successfully!

I can match by Id successfully as well.  Seems as though the error I encountered above was some cruft in the build.  So clean&rebuild cleared it.  

The tests are still a bit flaky, but this is solved
----------------------

I take your point about the setting separate instances for each SessionNavHostFragment.  For the moment, I'm having trouble figuring out where to instantiate it.  But that's a separate issue.  So I'll plug away for awhile longer.  If I really can't sort it out, perhaps I'll open a separate issue.

Many thanks for the feedback

**Comment by jayohms** [comment]
Perfect 👍

**Comment by graial** [comment]
@jayohms, thanks again.  Would you accept a pull request that puts an example in the demo app?

If so, please let me know how you'd like to see that play out.

Cheers

**Comment by jayohms** [comment]
@graial are you referring to an `espresso-web` test implementation? I am quite curious how you've used it, but we probably wouldn't merge anything that can't run on GitHub Actions.

**Comment by graial** [comment]
Yes, it'd be an androidInstrumentationTest.  So requires an android emulator.  

Is your current demo tested? I only see `debug` and `main` source sets and the `debug` only has a config file.

I was thinking to just add the code and readme instructions for running it from android studio.  Setting it up in CI/CD would be a bigger undertaking.

Setting up an android emulator in CI/CD is doable but I don't have a working example yet.  Most likely I'll be using Firebase for my project.

I've set-up CI/CD for a microcontroller project before using a self-hosted runners.  But this is [not a secure option for open-source repos](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#self-hosted-runner-security)

Here are a couple articles I've found that discuss emulator options for android.  If you are on-board with the emulator solution, it's easy enough to adapt the `.yml` to github actions.  But it'd really be up to what emulator option makes sense for this project.
 - https://dev.to/roselinebassey/android-automate-instrumented-and-unit-tests-with-circleci-1igo
 - https://ychescale9.medium.com/running-android-instrumented-tests-on-ci-from-bitrise-io-to-github-actions-a611e57ce71f

Plz let me know what makes sense to you from the above.

Cheers

**Comment by jayohms** [comment]
> I was thinking to just add the code and readme instructions for running it from android studio.

This is probably the most likely thing we'd worry about for now. Devs could run the tests on their own machines and the solution would mostly be for demo purposes. If you have time, could you submit something small and if looks useful to the library, it could be expanded further?

**Comment by graial** [comment]
Greetings @jayohms,

Just wanted to check in to see what you thought of the PR & if any questions/concerns.

Cheers
