### ISSUE TITLE
Access to fetch at `external_redirect_url` from origin `our_url` has been blocked due to CORS policy

### ISSUE THREAD

**Issue by hjhart** [hotwired/turbo-android#320]
Expected behavior: 

When tapping on a link that redirects to an external site
The external site should load correctly

Actual behavior: 

![Screenshot 2024-03-13 at 3 39 44 PM](https://github.com/hotwired/turbo-android/assets/547981/f48a9b50-7038-4a60-95af-816153951666)

"Error loading page" screen

Along with this in the Logcat output:

```
WebFragment onVisitErrorReceived() error code 0
```
```
[INFO:CONSOLE(0)] Access to fetch at 'https://our-app.formstack.com/forms/redacted' 
(redirected from 'http://app.android-local.dev-hellobrightline.com:3000/formstack/forms/3f76559e-bb49-4465-a7ab-ab4e75b80f29') 
from origin 'http://app.android-local.dev-hellobrightline.com:3000' has been blocked by CORS policy:
 No 'Access-Control-Allow-Origin' header is present on the requested resource. 
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.", 
source: http://app.android-local.dev-hellobrightline.com:3000/formstack/forms/3f76559e-bb49-4465-a7ab-ab4e75b80f29 (0)
```

Isolating the problem further, if instead I have the original link pointing to `https://our-app.formstack.com/forms/redacted` instead of `http://app.android-local.dev-hellobrightline.com:3000/formstack/forms/3f76559e-bb49-4465-a7ab-ab4e75b80f29`, it works just fine. The introduction of the redirect seems to break it. 

I noticed the CORS error in firefox and chrome, and disabling turbo fixed the request since it stopped being a `fetch` via turbo.js. Now it's happily a link that redirects successfully. But in our turbo-android app, it is still failing.

Since I don't have control over the formstack servers, I cannot modify the CORS headers successfully.

I'm going to continue to dive into this issue, but wanted to post it here for posterity, and to hopefully get some help from anyone who has encountered this issue previously.

Thanks in advance.

**Comment by MichalSznajder** [comment]
You have to intercept navigations to external links and create a separate WebView to show them. WebView from Turbo is only intended to be used with turbo.js itself.

**Comment by hjhart** [comment]
Thanks @MichalSznajder !

I already have some code doing that here:

```kotlin
interface NavDestination : TurboNavDestination {

   override fun shouldNavigateTo(newLocation: String): Boolean {
        Log.d("Navigation", "Navigation to ${newLocation} from ${location}")
        return when (isNavigable(newLocation)) {
            true -> true
            else -> {
                launchCustomTab(newLocation)
                false
            }
        }
    }

    private fun isNavigable(location: String): Boolean {
        return location.startsWith(BuildConfig.BASE_APP_URL)
    }

}
...

But the logging (Navigation to ${newLocation} from ${location}") only shows up on the first link. 

So it shows up for my internal link, returns true, and continues within the WebView with turbo.js. However, it does not log the above after the redirect. So, that mechanism fails here. It's very possible I'm inserting myself at the wrong moment, but if not, this is more internal to the `turbo-android` codebase than I've dug into.

I think we're getting closer. I'll keep looking through the docs to better understand if I'm intercepting the request properly.

**Comment by hjhart** [comment]
I think I've verified that this is a bug in `turbo-android`. I've added this commit to a fork of the demo repository: 

https://github.com/hjhart/turbo-native-demo/commit/767139cdc09d6c4181dd357860038b39ab65f742

You can see how the external links work just fine, but a redirect to an external link does now. See the video below, running against a local server and using the default turbo-android demo code.

https://github.com/hotwired/turbo-android/assets/547981/201cd83e-c7c4-4549-9257-3f7ebfcaa532

**Comment by hjhart** [comment]
@jayohms I'm happy to take this work on, as it is blocking my companies critical path, but do you have any pointers as to what code I might want to touch before I dive into this work?

**Comment by hjhart** [comment]
@jayohms, wow, that works perfectly. Thanks so much!

https://github.com/hotwired/turbo-android/assets/547981/46b22503-4ce2-4586-8db8-d6b9d64abdfe

**Comment by jayohms** [comment]
The fix is now available in 7.1.2: https://github.com/hotwired/turbo-android/releases/tag/7.1.2

**Comment by hjhart** [comment]
Hey @jayohms, thanks for the quick release! Does this also require an upgrade of turbo.js?

**Comment by hjhart** [comment]
@jayohms, okay, I'm realizing I don't know what to do again. The domain I had set up in test was to https://turbo.hotwired.dev. 

```
~ ❱ curl -I https://turbo.hotwired.dev                                                                                                                                                                                                                                                                                                                            13:43:19
HTTP/2 200
...
access-control-allow-origin: *
...
```

The important bit in those headers is that access-control-allow-origin is set to allow all domains. But how should the turbo-android package handle it if we don't have access to set those headers? One option is to set up a proxy, but I'd love to avoid setting up any new infrastructure, as this works perfectly fine in a browser.

Here it is demonstrated again...

https://github.com/hotwired/turbo-android/assets/547981/24b47cf0-7c38-4330-8a89-16dcf96cc3cb

I'm working off of `main` on turbo-android, and using this server running locally: https://github.com/hjhart/turbo-native-demo

I think I should be breaking out of turbo, but I don't seem to have the proper hooks firing to do so (shouldNavigateTo doesn't fire, for instance).

Any input?
