### ISSUE TITLE
Emulator doesn't seem to load external webpages

### ISSUE THREAD

**Issue by hjhart** [hotwired/turbo-android#326]
A note: This does seem to work on physical devices. This _used_ to work on emulators, I'm fairly certain. I tried running a bisect on previous commits but ran into various android studio / gradle compatibility issues. Before I dig too much deeper, I'm curious if others see this behavior.

Problem: When opening external links in chrome, the web page doesn't render properly. I can see the title render, but the page remains white. See the video below.

Expected: The web page should load successfully.

Method: Start the demo app (HEAD of `main`) inside of Android Studio and click on "Follow an external link".

https://github.com/hotwired/turbo-android/assets/547981/5c0c022e-9346-45c8-9aa4-0ab0387ead01

**Comment by jayohms** [comment]
What version of Chrome is installed on the emulator? My guess is it's an old version installed by default that doesn't support newer javascript APIs. I'd make sure you're using a Play Store emulator variant and you should be able to update Chrome if it's outdated.

**Comment by hjhart** [comment]
Okay, got it working after using a Pixel 8 play store variant instead of a Pixel 3a. Thanks for the advice @jayohms !
