### ISSUE TITLE
Browser version not supported error with new Rails

### ISSUE THREAD

**Issue by indigotechtutorials** [hotwired/turbo-android#347]
Rails added this feature which will block all unsupported browsers but this also is blocking the requests from turbo android apps
The only way I was able to get my android app the load the rails app was by commenting out the following line in the application controller
`allow_browser versions: :modern`

![Screenshot 2024-11-10 104251](https://github.com/user-attachments/assets/27d9307e-bd73-4580-a630-0badf959d8a1)
![Screenshot 2024-11-10 104233](https://github.com/user-attachments/assets/a8273586-79bb-4fc8-9cf0-8b34bf78bd63)

**Comment by joemasilotti** [comment]
It's blocking this request but the device is running an older version of Chrome. I'd recommend updating the emulator to a more recent version of Android or modifying `allow_browser` to [better fit your needs](https://github.com/rails/rails/pull/50505).
